=== panwoj/XMLClaimMapper/src/com/pirog/xmlParsers/xml/Claim/xml/Claim.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.pirog.com/claims" xmlns:tns="http://www.pirog.com/claims"
xmlns:com="http://www.example.org/common" elementFormDefault="qualified">
    <import schemaLocation="../../Common.xsd" namespace="http://www.example.org/common"/>
    <element name="Claim" type="tns:Claim"/>

    <complexType name="Claim">
        <sequence>
            <element name="LossInfo" type="tns:Loss"/>
            <element name="PolicyNumber" type="tns:policyString"/>
            <element name="Reporter" type="tns:Person" minOccurs="0" maxOccurs="unbounded"/>
            <element name="Claimant" type="tns:Person"/>
        </sequence>
        <attribute name="id" type="com:id" use="required"/>
    </complexType>

    <complexType name="Loss">
        <sequence>
            <element name="LossDate" type="dateTime"/>
            <element name="Incident" type="string"/>
            <element name="Severity" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Person">
        <sequence>
            <element name="Name" type="string"/>
            <element name="LastName" type="string"/>
            <element name="PhoneNumber" type="tns:phone"/>
        </sequence>
    </complexType>
    <simpleType name="policyString">
        <restriction base="string">
            <pattern value="[0-9]{5}-[A-Z]{2}"/>
        </restriction>
    </simpleType>
    <simpleType name="phone">
        <restriction base="string">
            <pattern value="[0-9]{3}-[0-9]{3}-[0-9]{3}"/>
        </restriction>
    </simpleType>
</schema>

=== panwoj/XMLClaimMapper/src/com/pirog/xmlParsers/xml/Claim/xml/ClaimWithTwoReporters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Claim xmlns="http://www.pirog.com/claims" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.pirog.com/claims Claim.xsd" id="1234">
    <LossInfo>
        <LossDate>2002-03-15T09:00:00</LossDate>
        <Incident>Car accident</Incident>
        <Severity>Serious</Severity>
    </LossInfo>
    <PolicyNumber>12345-XS</PolicyNumber>
    <Reporter>
        <Name>John</Name>
        <LastName>Big</LastName>
        <PhoneNumber>123-456-435</PhoneNumber>
    </Reporter>
    <Reporter>
        <Name>Tim</Name>
        <LastName>Alex</LastName>
        <PhoneNumber>333-333-321</PhoneNumber>
    </Reporter>
    <Claimant>
        <Name>Piotr</Name>
        <LastName>Siemasz</LastName>
        <PhoneNumber>555-333-222</PhoneNumber>
    </Claimant>
</Claim>

=== panwoj/XMLClaimMapper/src/com/pirog/xmlParsers/xml/Claim/xml/ClaimWithoutReporters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Claim xmlns="http://www.pirog.com/claims" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.pirog.com/claims Claim.xsd" id="5555">
    <LossInfo>
        <LossDate>2005-01-13T01:02:00</LossDate>
        <Incident>Window damage</Incident>
        <Severity>Not serious</Severity>
    </LossInfo>
    <PolicyNumber>12345-XS</PolicyNumber>
    <Claimant>
        <Name>Jacek</Name>
        <LastName>Pi≈Çka</LastName>
        <PhoneNumber>111-111-222</PhoneNumber>
    </Claimant>
</Claim>
